name: Deploy Static Page

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Slug do arquivo'
        required: true
      html_content:
        description: 'Conteúdo HTML em Base64'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar diretório de páginas (caso não exista)
        run: |
          mkdir -p pages

      - name: Criar arquivo HTML
        run: |
          echo "${{ inputs.html_content }}" | base64 --decode > pages/${{ inputs.slug }}.html

      - name: Configurar usuário do Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit e Push da nova página
        run: |
          git add pages/${{ inputs.slug }}.html
          git commit -m "Adicionando página ${{ inputs.slug }}"
          git push https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
