name: Deploy Static Page

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Slug do arquivo'
        required: true
      html_content:
        description: 'Conteúdo HTML em Base64'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Criar arquivo HTML
        run: |
          echo "${{ inputs.html_content }}" | base64 --decode > pages/${{ inputs.slug }}.html

      - name: Substituir placeholder pelo token
        run: |
          sed -i "s/PLACEHOLDER/${{ secrets.GH_TOKEN }}/g" pages/${{ inputs.slug }}.html

      - name: Verificar substituição do token
        run: |
          cat pages/${{ inputs.slug }}.html

      - name: Commit e Push da nova página
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pages/${{ inputs.slug }}.html
          git commit -m "Adicionando página ${{ inputs.slug }}"
          git push
