name: Deploy Static Page

on:
  workflow_dispatch: # Permite disparar manualmente pelo GitHub Actions
    inputs:
      slug:
        description: "Slug da página"
        required: true
      html_content:
        description: "Conteúdo HTML da página"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Criar diretório e salvar HTML
        run: |
          mkdir -p pages/${{ github.event.inputs.slug }}
          echo "${{ github.event.inputs.html_content }}" | base64 --decode > pages/${{ github.event.inputs.slug }}/index.html

      - name: Commit e Push das mudanças
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add pages/${{ github.event.inputs.slug }}/index.html
          git commit -m "Adicionando página: ${{ github.event.inputs.slug }}"
          git push https://x-access-token:$GH_TOKEN@github.com/Landowski/testes.git main
